### PR TITLE
Fix #138 delay resolving of publication artifacts.

### LINKED ISSUE #138: using maven-publish gradle plugin creates empty pom files
When using the new maven-publish plugin instead of the maven plugin, empty pom files are generated when pushing to artifactory. When using the same project and pushing to a local maven repo it works as expected.

Created a small test project: https://github.com/mouse256/artifactory-gradle-tests/tree/master/test1
* module1 is a java-library that uses maven-library: broken
* module1a is a copy that uses maven: works
* module2 is a java application with maven-library: also broken

### PR DESCRIPTION
**Pull request by steven-aerts**
The artifacts, dependency and other metadata was previously resolved
when the publication was specified to artifactory.
This can cause missing and/or incomplete pom files being uploaded to
artifactory.

### CODE REVIEW

**Comment by steven-aerts** [comment]
This fix is very related to #222 although they are independent and fix different things.

#138 is very easy to trigger in the latest versions of gradle when combined with the `maven-publish` plugin.

**Comment by eyalbe4** [comment]
@steven-aerts - thank you for this pull request.
I'm not sure I fully understand the scenario which cases this issue.
Can you please try to rephrase and elaborate more when describing the issue?

**Comment by eyalbe4** [comment]
Sorry @steven-aerts - I now see that you're referencing https://github.com/jfrog/build-info/issues/138

**Comment by eyalbe4** [comment]
@steven-aerts,
I tested the plugin with your changes with the [gradle-example-publish](https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-example-publish). I used gradle 4.8.1.
It failed with the following exception:
```
ip-10-1-20-183:gradle-example-publish eyalb$ gradle clean artifactoryPublish -S
> Task :artifactoryDeploy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artifactoryDeploy'.
> File '/Users/eyalb/dev/project-examples/gradle-examples/gradle-example-publish/api/build/libs/api-1.0-SNAPSHOT.jar' does not exist, and need to be published from publication ivyJava

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':artifactoryDeploy'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.api.GradleException: File '/Users/eyalb/dev/project-examples/gradle-examples/gradle-example-publish/api/build/libs/api-1.0-SNAPSHOT.jar' does not exist, and need to be published from publication ivyJava
        at org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications.createBuilder(TaskHelperPublications.java:317)
        at org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications.getArtifactDeployDetails(TaskHelperPublications.java:244)
        at org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications.collectDescriptorsAndArtifactsForUpload(TaskHelperPublications.java:202)
        at org.jfrog.gradle.plugin.artifactory.task.ArtifactoryTask.collectDescriptorsAndArtifactsForUpload(ArtifactoryTask.java:98)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.prepareAndDeploy(DeployTask.java:99)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.collectProjectBuildInfo(DeployTask.java:50)
        at org.jfrog.gradle.plugin.artifactory.task.DeployTask.taskAction(DeployTask.java:44)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 33 more


* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 0s

```

**Comment by steven-aerts** [comment]
Hi @eyalbe4,

even without my patch, I cannot get the examples working on the latest version of gradle.
So on the official version of the artifactory plugin, with a recent version of gradle (as I have to try both) I get:
```
FAILURE: Build failed with an exception.

* Where:
Build file '/tmp/project-examples/gradle-examples/gradle-example-publish/build.gradle' line: 124

* What went wrong:
A problem occurred configuring project ':api'.
> A problem occurred configuring project ':shared'.
   > Cannot notify listeners of type ProjectEvaluationListener as these listeners are already being notified.
```

More info/stacktrace in the gradle scan: https://scans.gradle.com/s/n5cxy3zeaierm

Can you confirm this is known/expected behaviour?

I will try do some further investigation.

**Comment by steven-aerts** [comment]
Hi @eyalbe4,

I did a better investigation of this bug and my patch on different gradle versions 
with or without my patch on [gradle-example-publish](https://github.com/jfrog/project-examples/tree/master/gradle-examples/gradle-example-publish).

First of all while investigation this bug, I found that the artifactory Sign task does exactly what we want but in
a [more elegant way](https://github.com/gradle/gradle/blob/master/subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java#L179).
So I updated my change, which hopefully does not have the troubles you are having.


### gradle 4.3.1 plugin version 4.9.6 :-(

This is the gradle version of the gradle wrapper included in the example project.

A pom is published, but its content is wrong for the api and the shared project.  The dependencies are missing so it hits #138.


### gradle 4.8.1 plugin version 4.9.6 :-(

In 4.8 the gradle publish plugin became stable and it is also the version you are referring to above to validate.

I run into #117: *Cannot notify listeners of type ProjectEvaluationListener as these listeners are already being notified.*.
So the same error as sait in my previous post from two days ago.

Gradle scan: https://gradle.com/s/tpjwv6jkbhjpm


### gradle 5.4.1 plugin version 4.9.6 :-(

This is the latest gradle version.

I also run into #117,  gradle scan: https://scans.gradle.com/s/n5cxy3zeaierm



### gradle 4.3.1 plugin version 4.9.x-SNAPSHOT :-(

Does not work, as the maven-publish plugin is a too early version and does not have the necessary methods.
Be aware that the maven-publish plugin only became stable on version 4.8.1.

@eyalbe4 is this ok for you?
 

### gradle 4.8.1 plugin version 4.9.x-SNAPSHOT :-)

Works nicely here.

### gradle 5.4.1 plugin version 4.9.x-SNAPSHOT :-)

Works nicely here.

### Conclusion

So with this new version of my plugin, I have the impression it does not only fix #138 but might also fix #117.


@eyalbe4 can you confirm the new version works better for you?  Do you still see problems?

Thanks,

   Steven

**Comment by eyalbe4** [comment]
Merged @steven-aerts.
Works perfectly! Awesome job!
Thank you!

**Comment by eyalbe4** [comment]
[GAP-299](https://www.jfrog.com/jira/browse/GAP-299) tracks this fix.

**Comment by eyalbe4** [comment]
@steven-aerts -
The fixed is released as part of version 4.9.7 of the plugin.
Thanks again for contributing this!

File: build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java [hunk 1]
```diff
@@ -150,19 +152,26 @@ public void checkDependsOnArtifactsToPublish() {
...
                 getProject().getPath(), capitalizedPublicationName));
         }
     }
 
+    private void dependOn(Publication publication) {
+        // TODO: Check how we can find the artifact dependencies without using internal api's.
+	// Based on org.gradle.plugins.signing.Sign#sign
+	PublicationInternal<?> publicationInternal = (PublicationInternal<?>) publication;
+	dependsOn((Callable<Set<? extends PublicationArtifact>>) publicationInternal::getPublishableArtifacts);
+	publicationInternal.allPublishableArtifacts(this::dependsOn);
```
Comment (grv87) [inline build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java]: @steven-aerts, are you sure this line is needed?
The previous line already added the whole collection.

Comment (steven-aerts) [reply build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/task/helper/TaskHelperPublications.java]: I agree with you, I think it might be possible to remove it.

As mentioned above for this code I based myself on Sigh#sign, which also does those [two steps](https://github.com/gradle/gradle/blob/master/subprojects/signing/src/main/java/org/gradle/plugins/signing/Sign.java#L176).

The second step is probably not needed, but kept it to be sure/the same.
